[package]
name = "entity"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }

[lib]
name = "entity"
path = "src/lib.rs"