[package]
name = "service"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
entity = { workspace = true }
sea-orm = { workspace = true }

[dev-dependencies]
tokio = { version = "1.20.0", features = ["macros", "rt"] }