[package]
name = "pojo"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
chrono = { workspace = true }

[lib]
name = "pojo"
path = "src/lib.rs"
