//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::book_info::Entity as BookInfo;
pub use super::post::Entity as Post;
pub use super::secret_info::Entity as SecretInfo;
pub use super::user::Entity as User;
